title: Waiman Meinhold # your name (or website title) here
logo: "/images/AutospineTest.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Medical robotics research, primarily MRI guided robots and rehabillitation robotics.
  <br><br>
I'm a robotics engineer dedicated to innovation and impactful contributions. My strong publication record, including work on predicting somatosensory evoked potentials and developing MRI-guided intraspinal injection systems, reflects my commitment to advancing robotics.

With accolades such as the 2023 Society of Instrument and Control Engineers (SICE) Young Authors award and the 2022 ASME Dynamic Systems and Control Division Rising Star award, I've consistently pushed boundaries and embraced technological advancements.

Proficient in all necessary components of robotic system development and evaluation, I bring a deep understanding of robotic technologies and systems. I hold a Ph.D in robotics along with my mechanical engineering Bachelor's degree, and have 7 years of experience developing novel robotic systems. 
  <br><br>
  <a href="https://www.linkedin.com/in/wmeinhold/">LinkedIn Profile</a> 
  <a href="https://www.linkedin.com/in/wmeinhold/">Resume</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here


