title: Waiman Meinhold # your name (or website title) here
logo: "/images/AutospineTest.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Medical robotics research, primarily MRI guided robots and rehabillitation robotics.
  <br><br>
 Currently a postdoctoral fellow in Mechanical Engineering at Georgia Institute of Technology. Based in Los Angeles. 
  <br><br>
  <a href="https://www.linkedin.com/in/wmeinhold/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here


